# Generated by Django 3.1.4 on 2020-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
